knp_paginator:
  default_options:
    page_name: page
    sort_field_name: psort
    sort_direction_name: porder
    distinct: true
    filter_field_name: filterField
    filter_value_name: filterValue
  template:
    pagination: '_assets/knp_paginator/pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig'
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template