framework:
    messenger:
        #failure_transport: failed
        transports:
            priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/priority_high'
            priority_normal:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/priority_normal'
            priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/priority_low'

        routing:
            App\Infrastructure\Message\Security\OTPCodeEmailMessage: priority_high
            App\Infrastructure\Message\Test\TestEmailMessage: priority_normal
