security:
    access_control:
        - { path: ^/fr/connexion.html$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/deconnexion.html$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/login.html$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/logout.html$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    enable_authenticator_manager: true

    password_hashers:
        App\Domain\_mysql\System\Entity\User:
            algorithm: auto

    providers:
        system_user_email_provider:
            entity:
                class: App\Domain\_mysql\System\Entity\User
                property: email
        system_user_token_provider:
            entity:
                class: App\Domain\_mysql\System\Entity\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            guard:
                authenticators:
                    - App\Application\Security\APIAuthenticator
            pattern: ^/api/v2
            provider: system_user_token_provider

        main:
            #guard:
            #    authenticators:
            #        - App\Application\Security\DefaultAuthenticator
            custom_authenticator: App\Application\Security\AppAuthenticator
            logout:
                path: app.security.logout
            provider: system_user_email_provider