version: "3.8"
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    image: mysql
    ports:
      - "11003:3306"
    restart: always
    volumes:
      - database-data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    links:
      - php
      - swagger
    ports:
      - "11001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
  node:
    build:
      context: ./docker/node
    command:
      - yarn run build
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: ['symfony', 'server:start', '--port=80']
    links:
      - database
    restart: always
    volumes:
      - .:/var/www
  phpmyadmin:
    depends_on:
      - database
    environment:
      PMA_HOST: database
    image: phpmyadmin
    restart: always
    ports:
      - "11002:80"
  swagger:
    environment:
      SWAGGER_JSON: /foo/swagger.json
    image: swaggerapi/swagger-ui
    volumes:
      - .:/foo
volumes:
  database-data: