version: "3.8"
services:
  apache2:
    build:
      context: ./docker/apache2
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "10001:80"
    restart: always
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./docker/apache2/sites-enabled/:/etc/apache2/sites-enabled/
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    image: mysql
    restart: always
    volumes:
      - database-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - database
    environment:
      PMA_HOST: database
    image: phpmyadmin
    restart: always
    ports:
      - "10002:80"
volumes:
  database-data: