version: "3.8"
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    image: mysql
    restart: always
    volumes:
      - database-data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    links:
      - php
    ports:
      - "11001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: ['symfony', 'server:start', '--port=80']
    links:
      - database
    restart: always
    volumes:
      - .:/var/www
  phpmyadmin:
    depends_on:
      - database
    environment:
      PMA_HOST: database
    image: phpmyadmin
    restart: always
    ports:
      - "11002:80"
volumes:
  database-data: