version: "3.8"
services:
  adminer:
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    image: adminer
    links:
      - database
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    image: mysql
    restart: always
    volumes:
      - database-data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    links:
      - adminer
      - php
      - s3server
      - swagger
    ports:
      - "10001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
  node:
    build:
      context: ./docker/node
    command:
      - yarn run build
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: ['symfony', 'server:start', '--port=80']
    links:
      - database
    restart: always
    volumes:
      - .:/var/www
  s3server:
    command: server /data --console-address ":9001"
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_CONSOLE}
      MINIO_ROOT_USER: ${MINIO_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    image: minio/minio
    ports:
      - "11004:9000"
      - "11005:9001"
    restart: unless-stopped
    volumes:
      - s3server-data:/data
  swagger:
    environment:
      SWAGGER_JSON: /foo/swagger.json
    image: swaggerapi/swagger-ui
    volumes:
      - .:/foo
volumes:
  database-data:
  s3server-data: