_default:
    resource: ../../src/UI/_default
    type: annotation

frontoffice:
    name_prefix: frontoffice.
    prefix:
        en: "/en/"
        fr: "/fr/"
    resource: ../../src/UI/FrontOffice
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
