_default:
    resource: ../../src/UI/_default
    type: annotation

frontoffice:
    name_prefix: frontoffice.
    prefix:
        en: "/en/"
        fr: "/fr/"
    resource: ../../src/UI/FrontOffice
    type: annotation

api_docs:
    name_prefix: api.docs.
    prefix: "/api/docs/"
    resource: ../../src/UI/API/Docs
    type: annotation

api_v2:
    name_prefix: api.v2.
    prefix: "/api/v2/"
    resource: ../../src/UI/API/V2
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
