parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Application\Annotation\Breadcrumb\BreadcrumbReader:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ['@annotation_reader']

    App\Application\Services\OTPService:
        arguments: ['@doctrine.orm.entity_manager', '@session']

    App\Application\Services\AWSS3Service:
        arguments:
            $endpoint: '%env(resolve:MINIO_ENDPOINT)%'
            $key: '%env(resolve:MINIO_KEY)%'
            $secret: '%env(resolve:MINIO_SECRET)%'

    App\Infrastructure\Profiler\PHPUnit\RequestProfiler:
        tags:
            - name: PHPUnit