name: Deploy on development server
on:
  push:
    branches: [develop]
jobs:
  init:
    runs-on: [development]
    steps:
      - name: Check directory exist
        id: check-directory
        continue-on-error: true
        run: |
          cd ./dev/
          echo ::set-output name=exist::true
      - name: Update exist project
        if: steps.check-directory.outputs.exist == 'true'
        run: |
          cd ./dev/
          git checkout master
          git add .
          git reset --hard
          git fetch origin --tags
          git pull
      - name: Deploy new project
        if: steps.check-directory.outputs.exist != 'true'
        run: |
          git clone git@github.com:tchevalleraud/symfony-docker-project.git
          mv symfony-docker-project/ dev/
          cd ./dev/
          git checkout master
      - name: Update environment
        run: |
          cd ./dev/
          rm -f .env
          touch .env
          echo "APP_ENV=dev" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          rm -f ./docker/.password
          echo "DATABASE_MYSQL_PASSWORD=${{ secrets.DATABASE_MYSQL_PASSWORD }}" >> ./docker/.password