name: Deploy on production server
on:
  push:
    branches: [master]
jobs:
  init:
    runs-on: [production]
    steps:
      - name: Check directory exist
        id: check-directory
        continue-on-error: true
        run: |
          cd ./prod/
          echo ::set-output name=exist::true
      - name: Update exist project
        if: steps.check-directory.outputs.exist == 'true'
        run: |
          cd ./prod/
          git checkout master
          git add .
          git reset --hard
          git fetch origin --tags
          git pull
      - name: Deploy new project
        if: steps.check-directory.outputs.exist != 'true'
        run: |
          git clone git@github.com:tchevalleraud/symfony-docker-project.git
          mv symfony-docker-project/ prod/
          cd ./prod/
          git checkout master
      - name: Update environment
        run: |
          cd ./prod/
          rm -f .env.local
          touch .env.local
          echo "APP_ENV=prod" >> .env.local
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
          echo "DATABASE_MYSQL_PASSWORD=${{ secrets.DATABASE_MYSQL_PASSWORD }}" >> .env.local
  build:
    runs-on: [production]
    needs: [init]
    steps:
      - name: Build docker image
        run: |
          cd ./prod/
          make docker-build
  deploy:
    runs-on: [production]
    needs: [build]
    steps:
      - name: Start docker environment
        run: |
          cd ./prod/
          make server-start
          sleep 30